# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      ORG_GRADLE_PROJECT_SONATYPE_USERNAME: "dummy"
      ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: "dummy"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          # noinspection UndefinedParamsPresent
          distribution: 'temurin'
          # noinspection UndefinedParamsPresent
          java-version: '21'
          # noinspection UndefinedParamsPresent
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon